CREATE DATABASE BD_GESTORNOTAS;

USE BD_GESTORNOTAS;

CREATE TABLE PERSONAS (
  idPersona VARCHAR(10) NOT NULL PRIMARY KEY,
  cedula VARCHAR(10) NOT NULL,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  correo VARCHAR(50) NOT NULL,
  celular VARCHAR(10) NOT NULL
);

CREATE TABLE USUARIOS(
  idUsuario VARCHAR(10) NOT NULL PRIMARY KEY,
  idPersona VARCHAR(10) NOT NULL,
  nickname VARCHAR(10) NOT NULL,
  pass VARCHAR(250) NOT NULL,
  rol VARCHAR(50) NOT NULL,
  FOREIGN KEY (idPersona) REFERENCES PERSONAS(idPersona)
);

CREATE TABLE CURSOS(
  idCurso VARCHAR(10) NOT NULL PRIMARY KEY,
  nombreCurso VARCHAR(100) NOT NULL
);

CREATE TABLE MATERIAS(
  idMateria VARCHAR(10) NOT NULL PRIMARY KEY,
  nombreMateria VARCHAR(10) NOT NULL,
  profesor VARCHAR(10) NOT NULL,
  FOREIGN KEY (profesor) REFERENCES USUARIOS(idUsuario)
);

CREATE TABLE MATERIASCURSOS(
  idMateriaCurso VARCHAR(10) NOT NULL PRIMARY KEY,
  idMateria VARCHAR(10) NOT NULL,
  idCurso VARCHAR(10) NOT NULL,
  FOREIGN KEY (idMateria) REFERENCES MATERIAS(idMateria),
  FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso)
);

CREATE TABLE ESTUDIANTESCURSOS(
  idEstudianteCurso VARCHAR(10) NOT NULL PRIMARY KEY,
  idEstudiante VARCHAR(10) NOT NULL,
  idCurso VARCHAR(10) NOT NULL,
  FOREIGN KEY (idEstudiante) REFERENCES USUARIOS(idUsuario),
  FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso)
);